custom question elements
KoftaCrew/NLP-Marker-Frontend pull request #10
Opened 2023-01-28 22:39 UTC by dovaaa

2023-01-28 22:42 UTC, dovaaa commented
I created some Custom elements, this is subject to change under changes to slate-types.d.ts, Do not merge yet

2023-01-30 15:30 UTC, KareemMAX requested changes

2023-01-30 15:30 UTC, KareemMAX commented on src/pages/editor/components/slate/slate-types.d.ts
> +export type QuestionElement =
I'm thinking `QuestionElement` should be structured differently, as it includes a question part/heading and an answer part.
So, `AnswerAreaElement` is not a valid alias, in fact `QuestionElement` as a whole should be renamed to something that represent a heading as I think that is what you wanna do. What do you think?

2023-01-30 15:30 UTC, KareemMAX commented on src/pages/editor/components/slate/slate-types.d.ts
> +export type MultipleChoiceQuestionElement = {
I think here we should denote an array of possible answers.

2023-02-15 01:27 UTC, dovaaa commented
![](https://github.trello.services/images/mini-trello-icon.png) [[GP-17] Create top level elements #10](https://trello.com/c/0gaOIZ6f/2-gp-17-create-top-level-elements-10)

2023-05-01 20:25 UTC, JonathanGhaly commented
Can I Contribute?

2023-06-19 03:17 UTC, CatB1t commented
Sure @JonathanGhaly

2023-06-25 11:16 UTC, closed without merging